# Generated by Django 4.2 on 2023-04-20 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='group',
            managers=[
            ],
        ),
    ]
